# Rename this file to languages.toml to enable multilingual support
[zh-cn]
contentDir = 'content/zh-cn'
languageName = '简体中文'
languagedirection = "ltr"
title = 'WaitBright Blog'
disabled = false
languageCode = 'zh-CN'
weight = 2

[en]
contentDir = 'content/en'
languageName = "English"
languagedirection = "ltr"
title = 'WaitBright Blog'
disabled = false
languageCode = 'en-US'
weight = 1
