# Configure main menu and social menu
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/WaitBright"

[social.params]
icon = "brand-github"

[[social]]
identifier = "weibo"
name = "weibo"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"
